# Generated by Django 5.0 on 2023-12-23 20:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_rename_post_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='epigrafe',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='comentarios',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='subtitulo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
