# Generated by Django 5.0 on 2023-12-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_remove_publicacion_epigrafe_publicacion_comentarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
