# Generated by Django 5.0 on 2023-12-23 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_curso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
